export const personalInfo = {
  name: "Ruisi Wang",
  affiliation: "SenseTime Research",
  university: "NTU Computer Science",
  email: "C200210@e.ntu.edu.sg",
  phone: "+65 91315875",
  tagline: "Computer Vision | Motion Capture | 3D Human Pose Estimation | High Performance Computing",
  bio: "I am a Researcher at SenseTime Research, interested in High Performance Computing, Motion Capture, 3D Human Pose Estimation, and Multimodal Models. I graduated with Honours (Highest Distinction) from Nanyang Technological University with a Bachelor of Engineering in Computer Science and a Minor in Mathematics. 🌟I am open for discussion/collaborations about spatial intelligence and video reasoning. If you think there is anything interesting we can discuss, feel free to email me!",
  googleScholar: "https://scholar.google.com/citations?user=4r07QUQAAAAJ&hl=en",
  linkedin: "https://www.linkedin.com/in/ruisi-wang-105737220/",
  github: "https://github.com/open-mmlab/mmhuman3d",
};

export const news = [
  {
    id: 11,
    date: "2026-03-25",
    content: "Video might be the next intelligence substrate. Strikingly, video models are beginning to exhibit the same emergent reasoning behaviors first observed in LLMs—multi-path search, self-correction, and layer specialization. We ",
    link: null,
    inlineLink: {
      text: "demystify video reasoning",
      url: "https://www.wruisi.com/demystifying_video_reasoning/",
    },
  contentAfter: " and show it doesn't happen frame-by-frame, but along diffusion steps.",
  },
  {
    id: 10,
    date: "2026-02-24",
    content: "Release of ",
    link: null,
    inlineLink: {
      text: "A Very Big Video Reasoning Suite",
      url: "https://video-reason.com/",
    },
    contentAfter: ", a comprehensive suite including million-scale video dataset, rule-based benchmark, strong baseline model that enables systematic training and evaluation of reasoning capabilities of video models.",
  },
  {
    id: 9,
    date: "2026-02-21",
    content: "Our work (",
    link: null,
    inlineLink: {
      text: "SenseNova-SI",
      url: "https://github.com/OpenSenseNova/SenseNova-SI",
    },
    contentAfter: ") got accepted to CVPR 2026! A paper is just a step. what truly matters is continuing to push the boundaries of spatial intelligence models and sharing our work with the community.",
  },
  {
    id: 8,
    date: "2026-01-26",
    content: "Our work (",
    link: null,
    inlineLink: {
      text: "ViMoGen",
      url: "https://motrixlab.github.io/2026_iclr_vimogen",
    },
    contentAfter: ") got accepted to ICLR 2026!",
  },
  {
    id: 7,
    date: "2025-12",
    content: "Update on SenseNova-SI: ",
    inlineLink: {
      text: "SenseNova-SI-1.2-InternVL3-8B",
      url: "https://huggingface.co/sensenova/SenseNova-SI-1.2-InternVL3-8B",
    },
    contentAfter: ", larger-scale, achieve state-of-the-art performance among open-source models of comparable size across eight recent spatial intelligence benchmarks: VSI, MMSI, MindCube, ViewSpatial, SITE, BLINK, 3DSRBench, EmbSpatial-Bench.",
  },
  {
    id: 6,
    date: "2025-11",
    content: "Release of SenseNova-SI: Scaling Spatial Intelligence with Multimodal Foundation Models.",
    link: "https://www.arxiv.org/abs/2511.13719",
  },
  {
    id: 5,
    date: "2025-10",
    content: "SMPLest-X: Ultimate Scaling for Expressive Human Pose and Shape Estimation accepted to TPAMI 2025.",
    link: "https://arxiv.org/abs/2501.09782",
  },
  {
    id: 4,
    date: "2024-08",
    content: "Joined SenseTime Research as a full-time Researcher.",
    link: null,
  },
  {
    id: 3,
    date: "2024-07",
    content: "One paper (WHAC) accepted to ECCV 2024.",
    link: "https://arxiv.org/abs/2403.12959",
  },
  {
    id: 2,
    date: "2024-02",
    content: "One paper (Digital Life Project) accepted to CVPR 2024.",
    link: "https://arxiv.org/abs/2312.04547",
  },
  {
    id: 1,
    date: "2023-06",
    content: "Won 1st Place in the Virtual ",
    link: null,
    inlineLink: {
      text: "HPC ISC2023 Student Cluster Competition",
      url: "https://www.ntu.edu.sg/computing/news-events/news/detail/first-time-champions-in-the-virtual-isc-student-cluster-competition-in-the-isc23",
    },
    contentAfter: ", leading NTU team to beat 19 teams worldwide.",
  },
];

export const researchThemes = [
  {
    id: 1,
    title: "Computer Vision",
    description: "Deep learning approaches for visual understanding, object detection, and image analysis.",
    icon: "Eye",
  },
  {
    id: 2,
    title: "High Performance Computing",
    description: "Optimizing and scaling AI workloads on supercomputers and clusters.",
    icon: "Cpu",
  },
  {
    id: 3,
    title: "Human Modeling",
    description: "Estimating 3D human body pose and shape from 2D images and videos.",
    icon: "User",
  },
  {
    id: 4,
    title: "Motion Generation",
    description: "Generating realistic human motion sequences using generative models.",
    icon: "Zap",
  },
  {
    id: 5,
    title: "Multimodal Foundation Models",
    description: "Large-scale models that understand and reason across multiple modalities.",
    icon: "Brain",
  },
  {
    id: 6,
    title: "Video Reasoning",
    description: "Temporal understanding and reasoning over video content.",
    icon: "Video",
  },
];

// Author annotation: "*" = co-first/equal contribution, "✉" = corresponding author
export type AuthorEntry = { name: string; annotation?: "*" | "✉" | "*✉" };

export const publications = [
  {
    id: 8,
    title: "Demystifing Video Reasoning",
    authors: [
      { name: "Ruisi Wang", annotation: "*" }, { name: "Zhongang Cai", annotation: "✉" }, { name: "Fanyi Pu" }, { name: "Junxiang Xu" },
      { name: "Wanqi Yin" }, { name: "Maijunxian Wang" }, { name: "Ran Ji" }, { name: "Chenyang Gu" },
      { name: "Bo Li" }, { name: "Ziqi Huang" }, { name: "Hokin Deng" }, { name: "Dahua Lin" },
      { name: "Ziwei Liu" }, { name: "Lei Yang" },
    ] as AuthorEntry[],
    venue: "arXiv 2026",
    year: 2026,
    citations: 0,
    type: "preprint",
    description: "Reasoning in video generation models happens along diffusion steps, not frames. We discover Chain-of-Steps — a new understanding of how video models think.",
    image: "/attached_assets/paper_teasers/2026_demystifying.jpg",
    arxiv: "https://arxiv.org/abs/2603.16870",
    github: "https://www.wruisi.com/demystifying_video_reasoning/",
  },
  {
    id: 7,
    title: "A Very Big Video Reasoning Suite",
    authors: [
      { name: "Maijunxian Wang", annotation: "*" }, { name: "Ruisi Wang", annotation: "*" }, { name: "Juyi Lin", annotation: "*" }, { name: "Ran Ji", annotation: "*" },
      { name: "Thaddäus Wiedemer" }, { name: "Qingying Gao" }, { name: "Dezhi Luo" }, { name: "Yaoyao Qian" },
      { name: "Lianyu Huang" }, { name: "Zelong Hong" }, { name: "Jiahui Ge" }, { name: "Qianli Ma" },
      { name: "Hang He" }, { name: "Yifan Zhou" }, { name: "Lingzi Guo" }, { name: "Lantao Mei" },
      { name: "Jiachen Li" }, { name: "Hanwen Xing" }, { name: "Tianqi Zhao" }, { name: "Fengyuan Yu" },
      { name: "Weihang Xiao" }, { name: "Yizheng Jiao" }, { name: "Jianheng Hou" }, { name: "Danyang Zhang" },
      { name: "Pengcheng Xu" }, { name: "Boyang Zhong" }, { name: "Zehong Zhao" }, { name: "Gaoyun Fang" },
      { name: "John Kitaoka" }, { name: "Yile Xu" }, { name: "Hua Xu" }, { name: "Kenton Blacutt" },
      { name: "Tin Nguyen" }, { name: "Siyuan Song" }, { name: "Haoran Sun" }, { name: "Shaoyue Wen" },
      { name: "Linyang He" }, { name: "Runming Wang" }, { name: "Yanzhi Wang" }, { name: "Mengyue Yang" },
      { name: "Ziqiao Ma" }, { name: "Raphaël Millière" }, { name: "Freda Shi" }, { name: "Nuno Vasconcelos" },
      { name: "Daniel Khashabi" }, { name: "Alan Yuille" }, { name: "Yilun Du" }, { name: "Ziming Liu" },
      { name: "Bo Li" }, { name: "Dahua Lin" }, { name: "Ziwei Liu" }, { name: "Vikash Kumar" },
      { name: "Yijiang Li" }, { name: "Lei Yang" }, { name: "Zhongang Cai", annotation: "✉" }, { name: "Hokin Deng", annotation: "✉" },
    ] as AuthorEntry[],
    venue: "arXiv 2026",
    year: 2026,
    citations: 1,
    type: "preprint",
    description: "A very big video reasoning suite including million-scale video dataset, rule-based benchmark, strong baseline model that enables systematic training and evaluation of reasoning capabilities of video models.",
    image: "/attached_assets/paper_teasers/2026_VBVR.jpg",
    arxiv: "https://arxiv.org/abs/2602.20159",
    github: "https://github.com/Video-Reason/VBVR-EvalKit",
  },
  {
    id: 6,
    title: "SenseNova-SI: Scaling Spatial Intelligence with Multimodal Foundation Models",
    authors: [
      { name: "Zhongang Cai" }, { name: "Ruisi Wang" }, { name: "Chenyang Gu" }, { name: "Fanyi Pu" },
      { name: "Junxiang Xu" }, { name: "Yubo Wang" }, { name: "Wanqi Yin" }, { name: "Zhitao Yang" },
      { name: "Chen Wei" }, { name: "Qingping Sun" }, { name: "Tongxi Zhou" }, { name: "Jiaqi Li" },
      { name: "Hui En Pang" }, { name: "Oscar Qian" }, { name: "Yukun Wei" }, { name: "Zhiqian Lin" },
      { name: "Xuanke Shi" }, { name: "Kewang Deng" }, { name: "Xiaoyang Han" }, { name: "Zukai Chen" },
      { name: "Xiangyu Fan" }, { name: "Hanming Deng" }, { name: "Lewei Lu" }, { name: "Liang Pan" },
      { name: "Bo Li" }, { name: "Ziwei Liu" }, { name: "Quan Wang" }, { name: "Dahua Lin" },
      { name: "Lei Yang" },
    ] as AuthorEntry[],
    venue: "CVPR 2026",
    year: 2025,
    citations: 8,
    type: "preprint",
    description: "State-of-the-art multimodal foundation model for spatial intelligence benchmarks.",
    image: "/attached_assets/paper_teasers/2025_sensenova-si.png",
    arxiv: "https://arxiv.org/abs/2511.13719",
    github: "https://github.com/OpenSenseNova/SenseNova-SI",
  },
  {
    id: 5,
    title: "The Quest for Generalizable Motion Generation: Data, Model, and Evaluation",
    authors: [
      { name: "Jing Lin", annotation: "*" }, { name: "Ruisi Wang", annotation: "*" }, { name: "Junzhe Lu", annotation: "*" }, { name: "Ziqi Huang" },
      { name: "Guorui Song" }, { name: "Ailing Zeng" }, { name: "Xian Liu" }, { name: "Chen Wei" },
      { name: "Wanqi Yin" }, { name: "Qingping Sun" }, { name: "Zhongang Cai" }, { name: "Lei Yang", annotation: "✉" },
      { name: "Ziwei Liu", annotation: "✉" },
    ] as AuthorEntry[],
    venue: "ICLR 2026",
    year: 2025,
    citations: 6,
    type: "preprint",
    description: "Comprehensive study on generalizable motion generation including data, model architecture, and evaluation methods.",
    image: "/attached_assets/paper_teasers/2025_ViMoGen.jpg",
    arxiv: "https://arxiv.org/abs/2510.26794",
    github: "https://github.com/motrixlab/ViMoGen",
  },
  {
    id: 4,
    title: "Holistic Evaluation of Multimodal LLMs on Spatial Intelligence (Previously: Has GPT-5 Achieved Spatial Intelligence? An Empirical Study)",
    authors: [
      { name: "Zhongang Cai" }, { name: "Yubo Wang" }, { name: "Qingping Sun" }, { name: "Ruisi Wang" },
      { name: "Chenyang Gu" }, { name: "Wanqi Yin" }, { name: "Zhiqian Lin" }, { name: "Zhitao Yang" },
      { name: "Chen Wei" }, { name: "Oscar Qian" }, { name: "Hui En Pang" }, { name: "Xuanke Shi" },
      { name: "Kewang Deng" }, { name: "Xiaoyang Han" }, { name: "Zukai Chen" }, { name: "Jiaqi Li" },
      { name: "Xiangyu Fan" }, { name: "Hanming Deng" }, { name: "Lewei Lu" }, { name: "Bo Li" },
      { name: "Ziwei Liu" }, { name: "Quan Wang" }, { name: "Dahua Lin" }, { name: "Lei Yang" },
    ] as AuthorEntry[],
    venue: "arXiv 2025",
    year: 2025,
    citations: 16,
    type: "preprint",
    description: "Comprehensive evaluation of spatial reasoning capabilities in large language models and multimodal systems.",
    image: "/attached_assets/paper_teasers/2025_easi.png",
    arxiv: "https://arxiv.org/abs/2508.13142",
  },
  {
    id: 3,
    title: "SMPLest-X: Ultimate Scaling for Expressive Human Pose and Shape Estimation",
    authors: [
      { name: "Wanqi Yin", annotation: "*" }, { name: "Zhongang Cai", annotation: "*" }, { name: "Ruisi Wang" }, { name: "Ailing Zeng" },
      { name: "Chen Wei" }, { name: "Qingping Sun" }, { name: "Haiyi Mei" }, { name: "Yanjun Wang" },
      { name: "Hui En Pang" }, { name: "Mingyuan Zhang" }, { name: "Lei Zhang" }, { name: "Chen Change Loy" },
      { name: "Atsushi Yamashita" }, { name: "Lei Yang", annotation: "✉" }, { name: "Ziwei Liu", annotation: "✉" },
    ] as AuthorEntry[],
    venue: "TPAMI 2025",
    year: 2025,
    citations: 27,
    type: "journal",
    description: "Scaling expressive human pose and shape estimation with large-scale training data and improved architectures.",
    image: "/attached_assets/paper_teasers/2025_smplestx.png",
    arxiv: "https://arxiv.org/abs/2501.09782",
  },
  {
    id: 2,
    title: "Digital Life Project: Autonomous 3D Characters with Social Intelligence",
    authors: [
      { name: "Zhongang Cai", annotation: "*" }, { name: "Jianping Jiang", annotation: "*" }, { name: "Zhongfei Qing", annotation: "*" }, { name: "Xinying Guo", annotation: "*" },
      { name: "Mingyuan Zhang" }, { name: "Zhengyu Lin" }, { name: "Haiyi Mei" }, { name: "Chen Wei" },
      { name: "Ruisi Wang" }, { name: "Wanqi Yin" }, { name: "Liang Pan" }, { name: "Xiangyu Fan" },
      { name: "Han Du" }, { name: "Peng Gao" }, { name: "Zhitao Yang" }, { name: "Yang Gao" },
      { name: "Jiaqi Li" }, { name: "Tianxiang Ren" }, { name: "Yukun Wei" }, { name: "Xiaogang Wang" },
      { name: "Chen Change Loy" }, { name: "Lei Yang", annotation: "✉" }, { name: "Ziwei Liu", annotation: "✉" },
    ] as AuthorEntry[],
    venue: "CVPR 2024",
    year: 2024,
    citations: 68,
    type: "conference",
    description: "Creating autonomous 3D digital humans with social intelligence capabilities for realistic virtual interactions.",
    image: "/attached_assets/paper_teasers/2024_digitallifeproject.png",
    arxiv: "https://arxiv.org/abs/2312.04547",
    github: "https://github.com/opendigitallife/digital_life_project",
  },
  {
    id: 1,
    title: "WHAC: World-Grounded Humans and Cameras",
    authors: [
      { name: "Wanqi Yin", annotation: "*" }, { name: "Zhongang Cai", annotation: "*" }, { name: "Ruisi Wang" }, { name: "Fanzhou Wang" },
      { name: "Chen Wei" }, { name: "Haiyi Mei" }, { name: "Weiye Xiao" }, { name: "Zhitao Yang" },
      { name: "Qingping Sun" }, { name: "Atsushi Yamashita" }, { name: "Ziwei Liu" }, { name: "Lei Yang" },
    ] as AuthorEntry[],
    venue: "ECCV 2024",
    year: 2024,
    citations: 32,
    type: "conference",
    description: "A framework for jointly estimating human models (SMPL-X) and camera poses from monocular video, using depth cues from human motion.",
    image: "/attached_assets/paper_teasers/2024_whac.jpg",
    arxiv: "https://arxiv.org/abs/2403.12959",
    github: "https://github.com/wangelin/WHAC",
  }
];

export const competitions = [
  {
    id: 6,
    title: "ISC2023 Student Cluster Competition",
    achievement: "1st Place",
    date: "Jun 2023",
    description: "Led the NTU team to beat 19 teams worldwide. Built, maintained, and utilized supercomputers; applied optimization techniques to complete real-world scientific workloads.",
    type: "hpc",
    category: "hpc",
    images: ["/attached_assets/competition_awards/2023_ISC_team_1.jpeg", "/attached_assets/competition_awards/2023_ISC_team_2.jpg", "/attached_assets/competition_awards/2023_ISC_all.jpg"],
  },
  {
    id: 5,
    title: "HPC AI Innovation Challenge 2023",
    achievement: "1st Place",
    date: "Jul 2024",
    description: "Competed in high performance computing AI innovation challenge. We also presented our winning solution at SCA2025 Supercomputing Asia.",
    type: "hpc",
    category: "ai",
    images: ["/attached_assets/competition_awards/2023_hpcaic_sca25.jpg"],
  },
  {
    id: 4,
    title: "Hack For Cities 2023",
    achievement: "1st Place",
    date: "Sep 2023",
    description: "Proposed innovative solution to tackle mobility issues using quantum computing.",
    type: "hackathon",
    category: "quantum",
    images: ["/attached_assets/competition_awards/2023_HFC_presentation.jpg"],
  },
  {
    id: 3,
    title: "SC2022 Student Cluster Competition",
    achievement: "Overall Runner-up & Best Poster",
    date: "Nov 2022",
    description: "Achieved second place overall and won best poster award at the international supercomputing competition.",
    type: "hpc",
    category: "hpc",
    images: ["/attached_assets/competition_awards/2022_SC_team_1.jpg", "/attached_assets/competition_awards/2022_SC_team_2.jpg", "/attached_assets/competition_awards/2022_SC_all.jpg"],
  },
  {
    id: 2,
    title: "ISC2022 Student Cluster Competition",
    achievement: "6th Overall",
    date: "Jun 2022",
    description: "Competed in the International Supercomputing Conference for HPC, Networking, and Storage.",
    type: "hpc",
    category: "hpc",
    images: [],
  },
  {
    id: 1,
    title: "35th Chinese Physics Olympiad",
    achievement: "National 2nd Prize & Provincial 1st Prize",
    date: "2018",
    description: "Awarded first prize in province and second prize at national level.",
    type: "academic",
    category: "physics",
    images: [],
  },
];

export const professionalService = {
  talks: [
    {
      id: 1,
      title: "SCA 2025 - HPCIC Winners Showcase Track session",
      description: "Presented winning solutions at the HPC Innovation Challenge showcase.",
    },
  ],
  eventOrganizer: [
    {
      id: 1,
      title: "TEDxNTU Main Organizer - Communications Department",
      description: "Organized events to expose potential change-makers to innovative speakers with creative and inspiring ideas.",
    },
    {
      id: 2,
      title: "OneArena 2022 Vice-President of Technical Department",
      description: "Hosted competitions and developed codes/games with RoboMaster EP. Mentored participants through workshops.",
    },
    {
      id: 3,
      title: "IET NTU On Campus Club Event Director",
      description: "Organized seminars and workshops to share technical knowledge with the NTU community.",
    },
  ],
  teaching: [
    {
      id: 1,
      title: "NTU School of Computer Science and Engineering (Now CCDS) Peer Coach",
      description: "Helped peer students overcome academic challenges and uplift them from 'Academically At-Risk' status.",
    },
  ],
};

export const education = [
  {
    id: 1,
    degree: "Bachelor of Engineering (Computer Science)",
    institution: "Nanyang Technological University, Singapore",
    period: "Aug 2020 - June 2024",
    honors: "Honours (Highest Distinction)",
    minor: "Minor in Mathematics",
    scholarship: "NTU Science and Engineering Undergraduate Scholarship",
    specialization: "Artificial Intelligence, High-Performance Computing, Data Science & Analytics",
  },
];

export const experience = [
  {
    id: 1,
    title: "Researcher",
    company: "SenseTime International Pte. Ltd.",
    period: "August 2024 - Present",
    responsibilities: [
      "Research on multimodal foundation models and spatial intelligence",
      "Development of SenseNova-SI achieving state-of-the-art on spatial benchmarks",
      "Video reasoning and 3D human pose estimation research",
    ],
  },
  {
    id: 2,
    title: "Research Internship",
    company: "SenseTime International Pte. Ltd.",
    period: "Dec 2023 - August 2024",
    responsibilities: [
      "SMPLest-X Human Pose and Shape Estimation base model development",
      "Research on expressive human pose and shape estimation",
      "Contributed to ECCV 2024 publication (WHAC)",
    ],
  },
  {
    id: 3,
    title: "Research Engineer Intern",
    company: "SenseTime International Pte. Ltd.",
    period: "May 2022 - Dec 2022",
    responsibilities: [
      "Post-processed data for better model training",
      "Investigated pruning techniques to reduce model size for faster inference",
      "Supported basketball and human body key points detection models",
      "Trained skiing posture detection models with 98% accuracy",
    ],
  },
  {
    id: 4,
    title: "Full Stack Developer",
    company: "Variantz Asia Pacific Pte. Ltd.",
    period: "Dec 2021 - Jan 2022",
    responsibilities: [
      "Built medical certificate system for issuing MC, keeping records and reports",
      "Enabled connection between system and health-related devices",
      "Backend: Nest.js, TypeORM; Frontend: Nuxt.js (Vue), Axios",
    ],
  },
];

export const awards = [
  { title: "Dean's List - Computer Science", date: "Aug 2022", description: "Top 5% of cohort in academic performance" },
  { title: "NTU President Research Scholar", date: "Jun 2022", description: "Accomplished with Merit in Undergraduate Research Programme (URECA)." },
];
